### PR TITLE
Remove break statements in switches

### LINKED ISSUE #17: Remove break statements in switches
Switches in Swift can have `break` statements in their cases. This is often used for cases that have no other statements, but it can in used in cases with multiple statements too:

```` Swift
switch number {
case 0:
	print("Hello!")
case 1:
	break
case 2:
	break
	print("Hello!")
default:
	print("Hello!")
	break
}
````

In the example above, Gryphon would currently include the `break` statements used on `case 2` and on `default`. This is a bug, since the Kotlin compiler would throw errors for these `break`s.

A correct translation would probably remove all `break` statements from switch cases. It should take care to raise a warning when there are statements after the `break` (as in `case 2`), otherwise the translated code would be incorrect (the Kotlin code would print "Hello" in `case 2` but the Swift code wouldn't).

### PR DESCRIPTION
**Pull request by pt2121**
Fixes #17 

I basically removed statements after `break` - I believe they are technically dead code. Is that what you expected?

### CODE REVIEW

**Comment by vinivendra** [comment]
This isn't what I had in mind, but I like your way better. My idea was to remove only the `breaks` and raise a warning for the other statements, but your idea of removing everything makes the translations more consistently correct. Also, Swift already raises a warning for statements after `breaks`, so we're covered there.

File: Sources/GryphonLib/KotlinTranslator.swift [hunk 1]
```diff
@@ -1009,8 +1009,12 @@ public class KotlinTranslator {
...
 			}
 
-			if switchCase.statements.count == 1,
-				let onlyStatement = switchCase.statements.first
+			let statements = switchCase.statements.prefix {
+					!($0 is BreakStatement)
+				}
+
+			if statements.count == 1,
+				let onlyStatement = statements.first
```
Comment (vinivendra) [inline Sources/GryphonLib/KotlinTranslator.swift:1017]: I think we could improve this by moving it from the `KotlinTranslator.swift` file to the `TranspilationPass.swift` file. Specifically, there's already a `RemoveBreaksInSwitchesTranspilationPass` class in there with a `removeBreaksInSwitchCase` method that might be a good fit for your changes.

This is just to make it consistent with the rest of the codebase: in general, all changes to the input code (like removing or adding statements) are made in the `TranspilationPasses`, so that the AST is ready to just be turned into text when it gets to the `KotlinTranslator`.

Comment (pt2121) [reply Sources/GryphonLib/KotlinTranslator.swift:1017]: Sounds good. I'll look into it. Thanks for the feedback.

Comment (pt2121) [reply Sources/GryphonLib/KotlinTranslator.swift]: Updated!

**Comment by vinivendra** [comment]
Thank you so much! This looks great. Just one more thing: could you change this pull request to target the `development` branch instead of `master`? I think it might be better to have day-to-day development on the `development` branch going forward, but I haven't yet had time to update this in the documentation (sorry about that).
There's a GitHub blog post that shows how to do that [here](https://github.blog/2016-08-15-change-the-base-branch-of-a-pull-request/), in case you're wondering.

**Comment by vinivendra** [comment]
It's done! Good work, and thanks.

**Comment by pt2121** [comment]
Awesome, thanks!
