### PR TITLE
issue #91 ✅

### LINKED ISSUE #91: Specify native warnings for Arrays and Dictionaries
**Describe the bug**
Specify native warnings for the following type of syntax:
```
let array: Array<Int> = Array()
let dictionary: Dictionary<String, Int> = Dictionary()
```

**Your environment (please complete the following information):**
 - OS: macOS
 - Gryphon version: 0.10.4

### PR DESCRIPTION
**Pull request by codersanjeev**
### What's in this pull request?
Created a string extension to check if a string is a declaration of an array or dictionary and used that to fix issue #91 

### Does this resolve an open issue?
Yeah, it resolves #91 .

### Checklist for submitting a pull request:

- [x] Your code builds without any errors or warnings (warnings when running `prepareForBootstrapTests.sh` are OK).
- [x] You ran the unit tests and Bootstrapping tests for your platform.
  - [ ] If you changed any `.kt` files in the `Test cases` folder, you also ran the Acceptance tests.
  
- [ ] You have added new tests that check your changes (if possible).
- [x] This pull request is targeting the `development` branch (if you're contributing code) or the `gh-pages` branch (if you're contributing to the website).

### CODE REVIEW

File: Sources/GryphonLib/Utilities.swift [hunk 1]
```diff
@@ -308,3 +308,21 @@ extension List {
 		return result
 	}
 }
+
+extension String {
+	func isArrayDeclaration() -> Bool {
+		if self.starts(with: "[") {
```
Comment (vinivendra) [inline Sources/GryphonLib/Utilities.swift]: If you choose to move this code to a translated file, I think you'll also have to change this method call.

Gryphon doesn't support translating `String.starts(with:)` yet, so this will cause a compilation error in Kotlin. You can either change this to `String.hasPrefix(_:)` or add a translation for `String.starts(with:)` in AuxiliaryFileContents.swift ([around here](https://github.com/vinivendra/Gryphon/blob/3601d30204875796f04aa55a7d9263d8bf00f0dc/Sources/GryphonLib/AuxiliaryFileContents.swift#L1476)).

File: Sources/GryphonLib/Utilities.swift [hunk 2]
```diff
@@ -308,3 +308,21 @@ extension List {
 		return result
 	}
 }
+
+extension String {
```
Comment (vinivendra) [inline Sources/GryphonLib/Utilities.swift]: Having the extension in this file is a problem for the BootstrappingTest. There is a `Utilities.swift` file and a separate `Utilities.kt` file (inside the `Bootstrap` folder), and the code inside them should be the same (in each language). This means if you want to keep this code here, you'll have to write a Kotlin version of it in `Utilities.kt` for the BootstrappingTest to work.

Or, if you prefer, you can move this code to a file that is translated automatically, like `SharedUtilities.swift` or `Extensions.swift`.

**Review by vinivendra — CHANGES_REQUESTED** [review]
Thanks for the PR 👍

I had a few problems with the bootstrapping test in my computer, did you run it on yours? You can do it with `./runTests.sh -b` in the terminal. In any case, I suggested a few changes to fix the problem.

Edit: Oops, looks like the comments below are out of order, I hope you can still understand them.

File: Sources/GryphonLib/Utilities.swift (hunk 2 above)
Comment (codersanjeev) [reply Sources/GryphonLib/Utilities.swift]: my bad, I missed it.

File: Sources/GryphonLib/Utilities.swift (hunk 1 above)
Comment (codersanjeev) [reply Sources/GryphonLib/Utilities.swift]: for now, I have moved the extension to SharedUtilities.swift file. the bootstrap tests are passing now.
If any further changes are required, most welcome.

File: Sources/GryphonLib/SharedUtilities.swift [hunk 3]
```diff
@@ -468,3 +468,22 @@ extension Utilities {
 		return nil
     }
 }
+
+extension String {
+	func isArrayDeclaration() -> Bool {
+		if self.starts(with: "[") {
```
Comment (vinivendra) [inline Sources/GryphonLib/SharedUtilities.swift]: I wonder why the bootstrap tests are passing for you, because they aren't passing for me... when I run `./runTests.sh -b` I get this compilation error:

````
Gryphon/Sources/GryphonLib/SharedUtilities.swift:474:11: error: unresolved reference: starts
    if (this.starts(with = "[")) {
             ^
````

That's because Gryphon doesn't know how to translate `self.starts(with: "[")`. I think you'll have to either replace this with `self.hasPrefix("[")` or teach Gryphon to translate it in [AuxiliaryFileContents.swift](https://github.com/vinivendra/Gryphon/blob/3601d30204875796f04aa55a7d9263d8bf00f0dc/Sources/GryphonLib/AuxiliaryFileContents.swift#L1476).

**Review by vinivendra — CHANGES_REQUESTED** [review]

File: Sources/GryphonLib/SharedUtilities.swift (hunk 3 above)
Comment (codersanjeev) [reply Sources/GryphonLib/SharedUtilities.swift]: I think I missed the -b flag while running the command, let me try it once again and do the required fixes.

Comment (codersanjeev) [reply Sources/GryphonLib/SharedUtilities.swift]: I have the required changes.

**Review by vinivendra — APPROVED** [review]

**Comment by vinivendra** [comment]
Great, that worked. Nice job 👍
